#run-OdsActionLogOt2DwdActionDoLog.job
type=command
command=sh spark-submit \
 --master yarn \
 --deploy-mode cluster \
 --num-executors 8 \
 --executor-memory 32G \
 --driver-memory 2G \
 --executor-cores 8 \
 --conf spark.yarn.maxAppAttempts=0 \
 --queue dwq \
 --class com.pep.dwd.OdsOriginalActionLog2DwdActionDoLogByDay \
 /root/pep-job/yunwang-dw-1.0-SNAPSHOT.jar 1
working.dir=/usr/local/azkaban/azkaban_work_dir/working_dir
dependencies=run-OSSLog2OriginalActionLog