#run-DwdProductUser2AdsPuserIncrease.job
type=command
command=sh spark-submit \
 --master yarn \
 --deploy-mode cluster \
 --num-executors 10 \
 --executor-memory 8G \
 --driver-memory 2G \
 --executor-cores 4 \
 --queue dwq \
 --conf spark.yarn.maxAppAttempts=0 \
 --class com.pep.ads.puser.DwdProductUser2AdsPuserIncrease \
 /root/pep-job/yunwang-dw-1.0-SNAPSHOT.jar
dependencies=run-OdsProductUser2DwdProductUser
working.dir=/usr/local/azkaban/azkaban_work_dir/working_dir