#run-DimLast30Day2DW.job
type=command
command=sh spark-submit \
 --master yarn \
 --deploy-mode cluster \
 --num-executors 2 \
 --executor-memory 8G \
 --driver-memory 2G \
 --executor-cores 4 \
 --queue dwq \
 --conf spark.yarn.maxAppAttempts=0 \
 --conf spark.yarn.executor.memoryOverhead=6000 \
 --class com.pep.dim.DimLast30Day2DW  \
 /root/pep-job/yunwang-dw-1.0-SNAPSHOT.jar
dependencies=run-DimCompanyData2DW
working.dir=/usr/local/azkaban/azkaban_work_dir/working_dir