create external table if not exists ods.ods_jxw_platform_p_textbook(
id                    string,
name                  string,
sub_heading           string,
rkxd                  string,
rkxd_name             string,
nj                    string,
nj_name               string,
zxxkc                 string,
zxxkc_name            string,
fascicule             string,
fascicule_name        string,
year                  string,
isbn                  string,
publisher             string,
chapter_json          string,
source_id             string,
ex_content_version    string,
down_times            string,
s_state               string,
s_creator             string,
s_creator_name        string,
s_create_time         string,
s_modifier            string,
s_modifier_name       string,
s_modify_time         string,
ex_books              string,
ex_booke              string,
ex_pages              string,
ed                    string,
publication_time      string,
folio                 string,
series                string,
content               string,
res_size              string,
tb_version            string,
res_version           string,
row_timestamp         string,
row_status            string
)
partitioned by (put_date string)
ROW FORMAT SERDE 'org.apache.hive.hcatalog.data.JsonSerDe'
stored as textfile location '/pep_cloud/business/ods/ods_jxw_platform_p_textbook';


create external table if not exists ods.ods_jxw_platform_p_resource(
id                            string,
keywords                      string,
resume                        string,
title                         string,
year                          string,
ex_zycj                       string,
dzwjlx                        string,
dzwjlx_name                   string,
zylx                          string,
zylx_name                     string,
yhlx                          string,
mtgslx                        string,
source_id                     string,
source_pid                    string,
source_app                    string,
source_batch                  string,
source_handler                string,
ori_tree_code                 string,
ori_tree_name                 string,
ori_tree_pos                  string,
s_edu_code                    string,
file_path                     string,
file_format                   string,
file_size                     string,
file_md5                      string,
file_ecry_type                string,
s_bak_flag                    string,
pic_pre_sum                   string,
pic_thumb_state               string,
s_state                       string,
s_creator                     string,
s_creator_name                string,
s_create_time                 string,
s_modifier                    string,
s_modifier_name               string,
s_modify_time                 string,
down_numb                     string,
score                         string,
ex_linktype                   string,
ex_linkcolor                  string,
ex_linksort                   string,
ex1                           string,
ex2                           string,
ex3                           string,
ex4                           string,
ex5                           string,
ex_turnpage                   string,
ex_gallery                    string,
ex_zynrlx                     string,
ex_zynrlx_name                string,
ex_rely                       string,
ex_content_version            string,
tb_id                         string,
jump_page                     string,
res_setting                   string,
relation_resinfo              string,
measure_resinfo               string,
res_group                     string,
view_numb                     string,
ex_jxsx                       string,
ex_page                       string,
ex_pos_description            string,
ex_limit_plat                 string,
ex_from                       string,
row_timestamp                 string,
row_status                    string
)
partitioned by (put_date string)
ROW FORMAT SERDE 'org.apache.hive.hcatalog.data.JsonSerDe'
stored as textfile location '/pep_cloud/business/ods/ods_jxw_platform_p_resource';