create table if not exists dwd_order_related_width(
order_id string,
detail_id string,
app_id string,
app_order_id string,
product_id string,
product_name string,
quantity string,
type string,
code string,
user_id string,
sale_channel_id string,
sale_channel_name string,
state string,
create_time string,
del_time string,
start_time string,
end_time string,
pay_time string,
discount string,
beans string,
material_code string,
material_name string,
pay_channel string,
pay_price string,
order_price string,
price string,
pay_tradeno string,
coupons string,
bean_type string,
remark string
) partitioned by (count_date string) 
stored as parquet;