#run-DwdActionDoLog2DwsDevice.job
type=command
command=sh spark-submit \
 --master yarn \
 --deploy-mode cluster \
 --num-executors 5 \
 --executor-memory 32G \
 --driver-memory 2G \
 --executor-cores 8 \
 --queue dwq \
 --conf spark.yarn.maxAppAttempts=0 \
 --class com.pep.dws.uv.DwdActionDoLog2DwsDevice \
 /root/pep-job/yunwang-dw-1.0-SNAPSHOT.jar
dependencies=run-DwsUv2AdsUv,run-DwsUvTotal2DwdUserArea
working.dir=/usr/local/azkaban/azkaban_work_dir/working_dir