#run-DwsUv2AdsUv.job
type=command
command=sh spark-submit \
 --master yarn \
 --deploy-mode cluster \
 --num-executors 10 \
 --executor-memory 8G \
 --driver-memory 2G \
 --executor-cores 4 \
 --queue dwq \
 --conf spark.yarn.maxAppAttempts=0 \
 --conf spark.yarn.executor.memoryOverhead=6000 \
 --class com.pep.ads.uv.DwsUv2AdsUvSummary \
 /root/pep-job/yunwang-dw-1.0-SNAPSHOT.jar
dependencies=run-DwdActionDoLog2DwsUv
working.dir=/usr/local/azkaban/azkaban_work_dir/working_dir